services:
  - type: web
    name: url-shortener
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BASE_URL
        value: https://xoragain.com
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GEOIP_DB_PATH
        value: data/GeoLite2-City.mmdb
      - key: PYTHON_VERSION
        value: "3.12"
